"""Optional Playwright-based auto-refresh for the Coveo search token.

Lifecycle:
  1. First call:  launches a HEADED Chromium window; user completes Workday login (incl. MFA).
                  We persist Playwright's storage_state to .playwright-state.json.
  2. Later calls: reuse the storage state in a HEADLESS Chromium; no UI.
  3. When headless fails (MFA challenge, expired session) or state ages out (~12h),
     fall back to the headed flow automatically.

This module is imported lazily — only when the user runs `bash bin/refresh-token.sh --auto`
or invokes `python -m community_mcp.auth`. The base MCP server has zero Playwright dependency.
"""

from __future__ import annotations

import json
import os
import time
import urllib.parse
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = PROJECT_ROOT / ".playwright-state.json"
ENV_FILE = PROJECT_ROOT / ".env"

STATE_MAX_AGE_HOURS = 12
HEADLESS_NAV_TIMEOUT_MS = 60_000
HEADED_LOGIN_TIMEOUT_MS = 5 * 60_000  # 5 min — give user time to handle MFA
COOKIE_WAIT_TIMEOUT_S = 60.0
COOKIE_POLL_INTERVAL_S = 0.5

ENTRY_URL = "https://community.workday.com/"
HOME_DOMAIN_FRAGMENT = "resourcecenter.workday.com"
COVEO_COOKIE_NAME = "coveo-info"

DEFAULT_ORG_ID = "workdayproductionurv9exm0"
DEFAULT_SEARCH_HUB = "IPE_AEM"


class AuthRefreshError(RuntimeError):
    """Raised when the browser-based refresh cannot extract a fresh search token."""


def _state_is_fresh() -> bool:
    if not STATE_FILE.exists():
        return False
    age_seconds = time.time() - STATE_FILE.stat().st_mtime
    return age_seconds < STATE_MAX_AGE_HOURS * 3600


def _wait_for_coveo_token(context, timeout_seconds: float = COOKIE_WAIT_TIMEOUT_S) -> str:
    """Poll the browser context cookies until coveo-info appears, then extract the token."""
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        for cookie in context.cookies(f"https://{HOME_DOMAIN_FRAGMENT}"):
            if cookie["name"] == COVEO_COOKIE_NAME and cookie["value"]:
                return _extract_search_token(cookie["value"])
        time.sleep(COOKIE_POLL_INTERVAL_S)
    raise AuthRefreshError(
        f"{COVEO_COOKIE_NAME} cookie did not appear within {timeout_seconds:.0f}s. "
        "MFA or session re-authentication may be required."
    )


def _extract_search_token(coveo_info_value: str) -> str:
    decoded = urllib.parse.unquote(coveo_info_value)
    payload = json.loads(decoded)
    token = payload.get("searchToken")
    if not token:
        raise AuthRefreshError("coveo-info cookie did not contain a searchToken")
    return token


def _write_env(search_token: str) -> None:
    ENV_FILE.write_text(
        "# Generated by community_mcp.auth (Playwright auto-refresh).\n"
        "# Do not commit. Re-run: bash bin/refresh-token.sh\n"
        f"COVEO_SEARCH_TOKEN={search_token}\n"
        f"COVEO_ORG_ID={DEFAULT_ORG_ID}\n"
        f"COVEO_SEARCH_HUB={DEFAULT_SEARCH_HUB}\n"
    )
    ENV_FILE.chmod(0o600)


def _do_browser_refresh(headless: bool) -> str:
    """Run a single browser session and return the fresh search token."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise AuthRefreshError(
            "Playwright is not installed. Run: uv pip install -e '.[auto-refresh]' "
            "&& playwright install chromium"
        ) from exc

    mode = "headless" if headless else "headed (please complete login in the browser window)"
    print(f"[auth] refresh mode: {mode}")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=headless)
        try:
            context_kwargs = {}
            if STATE_FILE.exists():
                context_kwargs["storage_state"] = str(STATE_FILE)
            context = browser.new_context(**context_kwargs)
            page = context.new_page()

            page.goto(ENTRY_URL)

            # Wait for the coveo-info cookie itself. It only appears after the full
            # login flow + Cloudflare clearance + AEM session + Coveo token fetch.
            # Matching on URL alone is unreliable: home.html can flash by during a
            # redirect chain BEFORE login completes.
            login_timeout_ms = HEADLESS_NAV_TIMEOUT_MS if headless else HEADED_LOGIN_TIMEOUT_MS
            search_token = _wait_for_coveo_token(context, timeout_seconds=login_timeout_ms / 1000)

            # Snapshot the now-fully-authenticated session for later headless reuse.
            context.storage_state(path=str(STATE_FILE))
        finally:
            browser.close()

    return search_token


def refresh_silent() -> str:
    """Headless-only refresh. Raises AuthRefreshError if MFA or re-login is needed.

    Called from the MCP server's auto-refresh path — we never open a browser
    mid-conversation. If this raises, the server surfaces a message telling the
    user to run `bash bin/refresh-token.sh` manually.
    """
    if not _state_is_fresh():
        raise AuthRefreshError(
            "Session expired (>12h). Run: bash bin/refresh-token.sh — "
            "a browser window will open for MFA login."
        )
    token = _do_browser_refresh(headless=True)
    _write_env(token)
    print(f"[auth] wrote {ENV_FILE} with fresh searchToken")
    return token


def refresh() -> str:
    """Full refresh: try headless first, fall back to headed if MFA is required.

    Called from `bash bin/refresh-token.sh`. Always succeeds as long as the user
    can complete the login (including MFA) in the browser window.
    """
    if _state_is_fresh():
        try:
            return refresh_silent()
        except AuthRefreshError:
            print("[auth] headless refresh failed — MFA or session expired. Opening browser...")
            STATE_FILE.unlink(missing_ok=True)

    token = _do_browser_refresh(headless=False)
    _write_env(token)
    print(f"[auth] wrote {ENV_FILE} with fresh searchToken")
    return token


if __name__ == "__main__":
    refresh()
